### ISSUE TITLE
[BUG] Error on fresh install

### ISSUE THREAD

**Issue by chexo3** [ArgosOfIthica/scalu#35]
**Describe the bug**
I get a fatal Python error when attempting to run the compiler.

```
C:\Users\<name>\Desktop\scalu>python scalu -m compile
Traceback (most recent call last):
File "C:\Users\<name>\scoop\apps\python\current\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None,
File "C:\Users\<name>\scoop\apps\python\current\lib\runpy.py", line 86, in _run_code exec(code, run_globals)
File "C:\Users\<name>\Desktop\scalu\scalu\__main__.py", line 1, in <module> from scalu.scalu import main
File "C:\Users\<name>\Desktop\scalu\scalu\scalu.py", line 1, in <module> import scalu.src.compiler as compiler
ModuleNotFoundError: No module named 'scalu.src'; 'scalu' is not a package
```

**Program that produces bug**
N/A, bug occurs with fresh install

**Expected behavior**
Scalu would compile the logo file present in scalu_in and generate output files to test.

**Environment (please complete the following information):**
 - OS: Windows, Python 3.10
 - Game: TF2
 - Version of Compiler: Most recent git commit as of writing

**Additional context**
Not sure what's going on here. Am I doing something wrong?

**Comment by ArgosOfIthica** [comment]
My apologies for this, I've been using the pip install standalone version and didn't notice the incorrect instructions. The proper command is `python -m scalu compile`.

**Comment by chexo3** [comment]
Oh that makes more sense now that I think of it
